Repository munkhtushig15/LYRO, pull requests merged in 2023-04, with the labels that each got.

#6 Duusagui backend
  BackEnd/.gitignore
  BackEnd/controller/blogs.js
  BackEnd/controller/users.js
  BackEnd/index.js
  BackEnd/model/Blog.js
  BackEnd/model/User.js
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/router/blog.js
  BackEnd/router/user.js
Labels: enhancement

#13 little change
  front/pages/Home.css
  front/pages/Home.jsx
  front/src/index.css
  front/src/pages/Home/Home.css
Labels: enhancement

#14 little change
  FrontEnd/.gitignore
  FrontEnd/README.md
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/pages/Home.css
  FrontEnd/pages/Home.jsx
  FrontEnd/public/favicon.ico
  FrontEnd/public/image 1.png
  FrontEnd/public/index.html
  FrontEnd/public/logo192.png
  FrontEnd/public/logo512.png
  FrontEnd/public/manifest.json
  FrontEnd/src/App.css
  FrontEnd/src/App.jsx
  FrontEnd/src/images/Frame 1.png
  FrontEnd/src/index.css
  FrontEnd/src/index.js
Labels: enhancement

#23 SignUp
  FrontEnd/src/App.jsx
  FrontEnd/src/comps/Header.jsx
  FrontEnd/src/pages/SignUp/SignUp.css
  FrontEnd/src/pages/SignUp/SignUp.jsx
Labels: enhancement

#24 Yes
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.css
  FrontEnd/src/App.jsx
  FrontEnd/src/pages/Login/Login.css
  FrontEnd/src/pages/Login/Login.jsx
Labels: enhancement

#27 Login done
  BackEnd/model/User.js
  FrontEnd/src/comps/Header.jsx
  FrontEnd/src/pages/Login/Login.jsx
  FrontEnd/src/pages/SignUp/SignUp.css
  FrontEnd/src/pages/SignUp/SignUp.jsx
Labels: enhancement

#32 little change
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/pages/CreatePost/Create.jsx
  FrontEnd/src/pages/Login/Login.css
  FrontEnd/src/pages/Login/Login.jsx
  FrontEnd/src/pages/SignUp/SignUp.css
  FrontEnd/src/pages/SignUp/SignUp.jsx
Labels: duplicate

#33 unsign
  FrontEnd/src/App.jsx
  FrontEnd/src/pages/Unsign/Unsign.css
  FrontEnd/src/pages/Unsign/Unsign.jsx
Labels: enhancement

#34 Little change
  FrontEnd/src/pages/Unsign/Unsign.css
  FrontEnd/src/pages/Unsign/Unsign.jsx
Labels: duplicate

#35 Another changes
  FrontEnd/src/App.jsx
  FrontEnd/src/pages/Login/Login.jsx
  FrontEnd/src/pages/SignUp/SignUp.jsx
  FrontEnd/src/pages/Unsign/Unsign.jsx
Labels: duplicate

#36 Blogs
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/public/index.html
  FrontEnd/src/App.css
  FrontEnd/src/comps/BigAds.jsx
  FrontEnd/src/comps/Blogs.jsx
  FrontEnd/src/images/travel.jpg
  FrontEnd/src/pages/Home/Home.css
  FrontEnd/src/pages/Home/Home.jsx
Labels: duplicate, enhancement

#43 Backend rating
  BackEnd/controller/blogs.js
  BackEnd/router/blog.js
Labels: enhancement

#44 Little change
  FrontEnd/src/pages/Login/Login.css
  FrontEnd/src/pages/Login/Login.jsx
  FrontEnd/src/pages/SignUp/SignUp.css
Labels: duplicate

#55 unsign aldaa zassan
  FrontEnd/src/pages/Unsign/Unsign.css
  FrontEnd/src/pages/Unsign/Unsign.jsx
Labels: documentation

#60 Start of 16 countries
  BackEnd/controller/blogs.js
  FrontEnd/src/App.css
  FrontEnd/src/App.jsx
  FrontEnd/src/comps/16 countries/Brazil.jsx
  FrontEnd/src/comps/16 countries/BrazilCont.jsx
  FrontEnd/src/comps/16 countries/China.jsx
  FrontEnd/src/comps/16 countries/ChinaCont.jsx
  FrontEnd/src/comps/16 countries/Mongolia.jsx
  FrontEnd/src/comps/16 countries/MongoliaCont.jsx
  FrontEnd/src/comps/Blogs.jsx
  FrontEnd/src/comps/Header.jsx
  FrontEnd/src/pages/Blog/City.jsx
  FrontEnd/src/pages/Blog/Mountian.jsx
  FrontEnd/src/pages/CreatePost/Create.jsx
  FrontEnd/src/pages/Home/Home.css
  FrontEnd/src/pages/Home/Home.jsx
Labels: enhancement

#61 8 16 countries fe
  BackEnd/controller/blogs.js
  BackEnd/controller/users.js
  BackEnd/model/Blog.js
  BackEnd/model/User.js
  BackEnd/router/blog.js
  FrontEnd/src/App.css
  FrontEnd/src/comps/16 countries/Brazil.jsx
  FrontEnd/src/comps/16 countries/BrazilCont.jsx
  FrontEnd/src/comps/16 countries/China.jsx
  FrontEnd/src/comps/16 countries/ChinaCont.jsx
  FrontEnd/src/comps/16 countries/Mongolia.jsx
  FrontEnd/src/comps/16 countries/MongoliaCont.jsx
  FrontEnd/src/comps/Header.jsx
  FrontEnd/src/pages/Blog/Blog.jsx
  FrontEnd/src/pages/Blog/City.jsx
  FrontEnd/src/pages/Blog/Mountian.jsx
  FrontEnd/src/pages/CreatePost/Create.jsx
  FrontEnd/src/pages/Home/Home.css
Labels: enhancement
